import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const analyticsStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  progressBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  progressBadgeText: {
    fontSize: 15,
    fontWeight: '700' as const,
  },
  weightTimeRange: {
    flexDirection: 'row' as const,
    gap: 8,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  weightTimeRangePill: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center' as const,
  },
  weightTimeRangeText: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  weightSection: {
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
  },
  weightHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  chartTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  chartIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  },
  chartSubtitle: {
    fontSize: 11,
    fontWeight: '500' as const,
    marginTop: 2,
    opacity: 0.7,
  },
  recordBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  recordBtnText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  weightStats: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
  },
  weightStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  weightStatDivider: {
    width: 1,
    height: 40,
  },
  weightStatValue: {
    fontSize: 24,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  weightStatLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginTop: 4,
  },
  weightChangeDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  emptyWeightState: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  emptyWeightText: {
    fontSize: 14,
    fontWeight: '500' as const,
    textAlign: 'center',
    lineHeight: 20,
  },
  weightGraphContainer: {
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
  },
  graphWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  graphYLabels: {
    width: 50,
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingRight: 8,
  },
  weightGraph: {
    position: 'relative',
    flex: 1,
  },
  graphDotTouchable: {
    position: 'absolute',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  graphDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  graphLine: {
    position: 'absolute',
    height: 2,
    borderRadius: 1,
    transformOrigin: 'left center',
  },
  targetGraphLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    borderRadius: 1,
    borderStyle: 'dashed',
  },
  graphLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  targetLabel: {
    fontWeight: '600' as const,
  },
  graphDateLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  graphDateLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  projectionCard: {
    marginTop: 16,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  projectionFriendlyText: {
    fontSize: 15,
    fontWeight: '600' as const,
    marginBottom: 4,
    lineHeight: 22,
  },
  projectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  estimatedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginLeft: 'auto',
  },
  estimatedBadgeText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: '#F59E0B',
  },
  projectionTitle: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  projectionContent: {
    gap: 2,
  },
  projectionDate: {
    fontSize: 17,
    fontWeight: '700' as const,
  },
  projectionSubtext: {
    fontSize: 12,
    fontWeight: '500' as const,
  },
  projectionMessage: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  chartCard: {
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  targetBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  targetBadgeText: {
    fontSize: 11,
    fontWeight: '600' as const,
  },
  chartContainer: {
    position: 'relative',
  },
  targetLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  targetLineDash: {
    flex: 1,
    height: 1,
    opacity: 0.4,
  },
  barsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: '100%',
    paddingTop: 24,
  },
  barColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    maxWidth: 50,
  },
  bar: {
    width: '65%',
    minHeight: 4,
    maxWidth: 24,
  },
  barLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
    textAlign: 'center',
  },
  barValue: {
    fontSize: 10,
    fontWeight: '600' as const,
    height: 14,
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 24,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 12,
    fontWeight: '500' as const,
  },
  macroListContainer: {
    gap: 16,
  },
  macroListItem: {
    gap: 10,
  },
  macroListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  macroListLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  macroColorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  macroListName: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  macroListRight: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
  },
  macroListValue: {
    fontSize: 17,
    fontWeight: '700' as const,
  },
  macroListTarget: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  macroProgressBg: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  macroProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  statCard: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
  },
  statIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
    marginTop: 4,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: '500' as const,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: SCREEN_WIDTH - 48,
    borderRadius: 14,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 0,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    padding: 20,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    marginBottom: 10,
  },
  datePickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
  },
  dateNavBtn: {
    padding: 14,
  },
  dateDisplay: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
  },
  dateDisplayText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  weightInputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  weightInput: {
    flex: 1,
    height: 60,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 20,
    fontSize: 28,
    fontWeight: '700' as const,
    textAlign: 'center',
  },
  weightInputLarge: {
    height: 60,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 20,
    fontSize: 30,
    fontWeight: '800' as const,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  weightUnitBox: {
    width: 60,
    height: 60,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weightUnit: {
    fontSize: 18,
    fontWeight: '600' as const,
  },
  datePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 14,
    borderWidth: 1,
  },
  datePickerButtonText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600' as const,
  },
  weightError: {
    color: '#C53030',
    fontSize: 13,
    fontWeight: '600' as const,
    marginTop: 10,
  },
  currentWeightHint: {
    fontSize: 13,
    fontWeight: '500' as const,
    marginTop: 16,
    textAlign: 'center',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    paddingTop: 8,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  editDateLabel: {
    fontSize: 15,
    fontWeight: '600' as const,
    textAlign: 'center',
  },
  editModalFooter: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
    paddingTop: 8,
  },
  deleteWeightBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 10,
    borderWidth: 1,
  },
  deleteWeightBtnText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#C53030',
  },
  calendarModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarModalContent: {
    width: SCREEN_WIDTH - 48,
    borderRadius: 14,
    padding: 20,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  calendarNavBtn: {
    padding: 8,
  },
  calendarMonthText: {
    fontSize: 18,
    fontWeight: '700' as const,
  },
  calendarWeekdays: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  calendarWeekday: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600' as const,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: '14.2857%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  calendarDaySelected: {
    backgroundColor: '#6C63FF',
  },
  calendarDayToday: {
    borderWidth: 2,
  },
  calendarDayText: {
    fontSize: 15,
    fontWeight: '500' as const,
  },
  calendarDayTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700' as const,
  },
  streakRow: {
    flexDirection: 'row' as const,
    gap: 10,
    marginBottom: 16,
  },
  streakCardLeft: {
    flex: 3,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    alignItems: 'center' as const,
    gap: 6,
  },
  streakCardRight: {
    flex: 2,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
  },
  streakCardNumber: {
    fontSize: 28,
    fontWeight: '800' as const,
    letterSpacing: -1,
  },
  streakCardLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  weekDotsRow: {
    flexDirection: 'row' as const,
    gap: 6,
    marginTop: 8,
  },
  weekDotCol: {
    alignItems: 'center' as const,
    gap: 4,
  },
  weekDotDayLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
  },
  weekDotCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  changeRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 14,
    gap: 10,
  },
  changeLabel: {
    fontSize: 14,
    fontWeight: '500' as const,
    width: 60,
  },
  changeTrendBar: {
    width: 32,
    height: 16,
    borderRadius: 4,
  },
  changeValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    flex: 1,
    textAlign: 'right' as const,
  },
  changeTrend: {
    fontSize: 13,
    fontWeight: '600' as const,
    width: 72,
    textAlign: 'right' as const,
  },
  energyStatsRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 20,
  },
  energyStat: {
    alignItems: 'center' as const,
    flex: 1,
  },
  energyStatLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginBottom: 4,
  },
  energyStatValue: {
    fontSize: 20,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  energyStatUnit: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginTop: 2,
  },
  energyChartArea: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-end' as const,
    paddingBottom: 24,
  },
  energyBarCol: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    gap: 6,
  },
  energyBarPair: {
    flexDirection: 'row' as const,
    alignItems: 'flex-end' as const,
    gap: 3,
  },
  energyBar: {
    width: 14,
    borderRadius: 4,
    minHeight: 3,
  },
  energyDayLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
  },
  bmiCard: {
    borderRadius: 12,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
  },
  bmiHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 12,
  },
  bmiTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  },
  bmiValueRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginBottom: 20,
  },
  bmiValueText: {
    fontSize: 36,
    fontWeight: '800' as const,
    letterSpacing: -1,
  },
  bmiBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  bmiBadgeText: {
    fontSize: 14,
    fontWeight: '700' as const,
  },
  bmiScaleWrapper: {
    position: 'relative' as const,
    marginBottom: 20,
    height: 20,
  },
  bmiScaleBar: {
    flexDirection: 'row' as const,
    height: 10,
    borderRadius: 5,
    overflow: 'hidden' as const,
    marginTop: 5,
  },
  bmiSegment: {
    height: '100%' as const,
  },
  bmiPointer: {
    position: 'absolute' as const,
    top: 0,
    width: 3,
    height: 20,
    marginLeft: -1.5,
  },
  bmiPointerLine: {
    width: 3,
    height: 20,
    borderRadius: 1.5,
  },
  bmiLegendRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
  },
  bmiLegendCol: {
    alignItems: 'center' as const,
    gap: 3,
  },
  bmiLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  bmiLegendLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
  },
  bmiLegendRange: {
    fontSize: 10,
    fontWeight: '500' as const,
  },
  emptyPhotoState: {
    alignItems: 'center' as const,
    paddingVertical: 28,
    borderWidth: 1,
    borderStyle: 'dashed' as const,
    borderRadius: 12,
  },
  emptyPhotoIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: 12,
  },
  emptyPhotoTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  emptyPhotoText: {
    fontSize: 13,
    fontWeight: '500' as const,
    textAlign: 'center' as const,
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  photoScroll: {
    marginHorizontal: -4,
  },
  photoCard: {
    marginHorizontal: 4,
    alignItems: 'center' as const,
    gap: 6,
  },
  photoImageWrap: {
    width: 90,
    height: 120,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
  },
  photoPlaceholder: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  photoDateLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  photoModalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
    width: '100%' as const,
  },
  photoModalHandle: {
    alignItems: 'center' as const,
    marginBottom: 20,
  },
  photoModalHandleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
  },
  photoModalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  photoModalSubtitle: {
    fontSize: 14,
    fontWeight: '500' as const,
    marginBottom: 24,
  },
  photoModalOption: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 14,
    padding: 16,
    borderRadius: 14,
    marginBottom: 10,
  },
  photoModalIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  photoModalOptionText: {
    flex: 1,
    gap: 2,
  },
  photoModalOptionTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  photoModalOptionDesc: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  photoModalCancel: {
    marginTop: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center' as const,
  },
  photoModalCancelText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  fotoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  fotoBtnText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  waterTrendRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 10,
  },
  waterTrendLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  waterTrendLabel: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  waterTrendSub: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginTop: 1,
  },
  waterTrendRight: {
    flexDirection: 'row' as const,
    alignItems: 'baseline' as const,
    gap: 2,
  },
  waterTrendValue: {
    fontSize: 22,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  waterTrendTarget: {
    fontSize: 14,
    fontWeight: '500' as const,
  },
  waterProgressBg: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden' as const,
    marginBottom: 4,
  },
  waterProgressFill: {
    height: '100%' as const,
    borderRadius: 4,
  },
  microsDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.05)',
    marginVertical: 16,
  },
  microRow: {
    gap: 8,
    marginBottom: 14,
  },
  microRowHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  microRowLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  microColorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  microRowName: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  microRowRight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 3,
  },
  microRowAvg: {
    fontSize: 16,
    fontWeight: '700' as const,
  },
  microRowTarget: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  microGoodBadge: {
    fontSize: 13,
    color: '#22C55E',
    fontWeight: '700' as const,
    marginLeft: 4,
  },
  microProgressBg: {
    height: 5,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  microProgressFill: {
    height: '100%' as const,
    borderRadius: 3,
  },
  activityStatsRow: {
    flexDirection: 'row' as const,
    gap: 8,
    marginBottom: 16,
  },
  activityStatCard: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center' as const,
    gap: 4,
  },
  activityStatValue: {
    fontSize: 18,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  activityStatLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  activityMiniProgress: {
    height: 4,
    borderRadius: 2,
    overflow: 'hidden' as const,
    width: '100%' as const,
    marginTop: 4,
  },
  activityMiniProgressFill: {
    height: '100%' as const,
    borderRadius: 2,
  },
  activityBurnBreakdown: {
    alignItems: 'center' as const,
    marginTop: 2,
  },
  activityBurnDetail: {
    fontSize: 10,
    fontWeight: '500' as const,
  },
  stepsChartSection: {
    marginBottom: 8,
  },
  stepsChartTitle: {
    fontSize: 13,
    fontWeight: '600' as const,
    marginBottom: 12,
  },
  stepsChartArea: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-end' as const,
    paddingBottom: 24,
  },
  stepsBarCol: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    gap: 4,
  },
  stepsBar: {
    width: '55%' as const,
    borderRadius: 6,
    maxWidth: 24,
  },
  stepsBarValue: {
    fontSize: 9,
    fontWeight: '600' as const,
  },
  stepsDayLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  activityAvgRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingTop: 14,
    borderTopWidth: 1,
  },
  activityAvgItem: {
    flex: 1,
    alignItems: 'center' as const,
    gap: 2,
  },
  activityAvgLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  activityAvgValue: {
    fontSize: 15,
    fontWeight: '700' as const,
  },
  activityAvgDivider: {
    width: 1,
    height: 28,
  },
});
