import { StyleSheet, Dimensions } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const CAROUSEL_CARD_WIDTH = SCREEN_WIDTH - 28;

export const indexStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateNavButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateCenter: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  dateTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calendarModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  calendarModalContent: {
    borderRadius: 14,
    padding: 20,
    width: '100%',
    maxWidth: 360,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarNavBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: {
    fontSize: 18,
    fontWeight: '700' as const,
  },
  calendarWeekdays: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  calendarWeekday: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600' as const,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: '14.28%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  calendarDaySelected: {
    backgroundColor: '#6C63FF',
  },
  calendarDayToday: {
    borderWidth: 2,
  },
  calendarDayText: {
    fontSize: 15,
    fontWeight: '500' as const,
  },
  calendarDayTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700' as const,
  },
  todayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  todayButtonText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  appNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  appLogo: {
    width: 32,
    height: 32,
  },
  appName: {
    fontSize: 26,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },

  dateText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(180, 83, 9, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  streakText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#B45309',
  },
  motivationalToast: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    zIndex: 1000,
  },
  motivationalToastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6C63FF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  motivationalToastWarning: {
    backgroundColor: '#92400E',
  },
  motivationalToastCelebration: {
    backgroundColor: '#6C63FF',
  },
  motivationalToastEmoji: {
    fontSize: 20,
  },
  motivationalToastText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#FFFFFF',
    lineHeight: 20,
  },
  content: {
    flex: 1,
  },
  topCardsSection: {
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 16,
  },
  calorieCard: {
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
  },
  macroSeparateCard: {
    flex: 1,
    borderRadius: 14,
    padding: 14,
    paddingVertical: 18,
    alignItems: 'center' as const,
    gap: 10,
  },
  macroCardEmoji: {
    fontSize: 15,
  },
  macroCardValues: {
    flexDirection: 'row' as const,
    alignItems: 'baseline' as const,
    gap: 2,
  },
  macroCardCurrent: {
    fontSize: 18,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  macroCardTarget: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  macroCardFooter: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  macroCardName: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  macroCardPctBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  macroCardPctText: {
    fontSize: 11,
    fontWeight: '700' as const,
  },
  sideBySideRow: {
    flexDirection: 'row' as const,
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 16,
  },
  sideBySideCardLeft: {
    flex: 1,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    gap: 10,
  },
  sideBySideCardRight: {
    width: 140,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    gap: 0,
  },
  microVerticalList: {
    gap: 12,
  },
  microVerticalItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  microVerticalValue: {
    fontSize: 11,
    fontWeight: '700' as const,
  },
  microVerticalInfo: {
    flex: 1,
    gap: 1,
  },
  microVerticalLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  microVerticalTarget: {
    fontSize: 10,
    fontWeight: '500' as const,
  },
  microWaterDivider: {
    height: 1,
    alignSelf: 'stretch' as const,
    marginVertical: 12,
  },
  waterCardExpanded: {
  },
  waterCompactExpanded: {
    flex: 1,
    gap: 12,
    justifyContent: 'center' as const,
  },
  waterHeaderExpanded: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  waterIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(56,189,248,0.1)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  waterHeaderTextCol: {
    flex: 1,
    gap: 1,
  },
  waterTitleExpanded: {
    fontSize: 14,
    fontWeight: '700' as const,
  },
  waterSubtitleExpanded: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  waterPctBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  waterPctText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#38BDF8',
  },
  waterProgressBarWrap: {
    paddingVertical: 2,
  },
  waterProgressBarBg: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  waterProgressBarFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#38BDF8',
  },
  waterControlsExpanded: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  premiumMaskOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    overflow: 'hidden' as const,
    zIndex: 30,
  },
  premiumMaskSection: {
    position: 'relative' as const,
    borderRadius: 16,
    overflow: 'hidden' as const,
  },
  premiumMaskDim: {
    flex: 1,
    backgroundColor: 'rgba(20,20,20,0.42)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  premiumMaskBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  premiumMaskText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  waterBtnExpanded: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 1,
    borderColor: 'transparent' as const,
  },
  waterDotsExpanded: {
    flex: 1,
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    justifyContent: 'center' as const,
    gap: 5,
  },
  waterDotExpanded: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  activitySeparateRow: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  activitySeparateCard: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 18,
    paddingHorizontal: 8,
    gap: 8,
  },
  activitySeparateIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  activitySeparateVal: {
    fontSize: 18,
    fontWeight: '700' as const,
  },
  activitySeparateLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  activityMiniStatsCompact: {
    flexDirection: 'row' as const,
    gap: 6,
  },
  activityMiniStatCompact: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderRadius: 8,
  },
  activityMiniStatValCompact: {
    fontSize: 11,
    fontWeight: '700' as const,
  },
  exCardHeaderRow: {
    marginBottom: 8,
  },
  exCardTitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  },
  exCardSubtitle: {
    fontSize: 10,
    fontWeight: '400' as const,
    marginTop: 1,
  },
  exFixedContent: {
    flex: 1,
    minHeight: 105,
    justifyContent: 'center' as const,
  },
  exModeTabsCompact: {
    flexDirection: 'row' as const,
    borderRadius: 8,
    padding: 2,
    marginBottom: 8,
  },
  exModeTabCompact: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 3,
    paddingVertical: 5,
    borderRadius: 6,
  },
  exQuickContentCompact: {
    gap: 8,
  },
  exQuickScrollContent: {
    paddingVertical: 4,
    gap: 10,
  },
  exQuickGridChip: {
    width: 90,
    height: 100,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
  },
  exQuickInputRowCompact: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  exQuickInputCompact: {
    flex: 1,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    fontSize: 13,
  },
  exLogBtnCompact: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#4CAF7D',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  exDescribeContentCompact: {
    gap: 6,
  },
  exDescribeInputRowCompact: {
    flexDirection: 'row' as const,
    alignItems: 'flex-end' as const,
    gap: 6,
  },
  exDescribeInputFixed: {
    flex: 1,
    height: 90,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    lineHeight: 20,
  },
  exManualContentTight: {
    gap: 6,
  },
  exManualRowTight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
  },
  exManualInputTight: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
  },
  carouselContainer: {
    marginBottom: 16,
    marginTop: 4,
  },
  carouselPageContainer: {
    width: CAROUSEL_CARD_WIDTH,
    gap: 8,
  },
  separatedCard: {
    borderRadius: 18,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  heroCardTaller: {
    minHeight: 200,
  },
  heroCardOutlined: {
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  heroRingOuterBorder: {
    borderWidth: 2,
    borderRadius: 999,
    padding: 4,
  },
  heroSimpleDivider: {
    height: 1,
    alignSelf: 'stretch' as const,
    marginVertical: 2,
  },
  carouselCard: {
    width: CAROUSEL_CARD_WIDTH,
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    alignItems: 'center' as const,
    gap: 0,
  },
  microCarouselContent: {
    gap: 12,
  },
  microCarouselRow: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  microCarouselItem: {
    flex: 1,
    alignItems: 'center' as const,
    gap: 8,
  },
  microCarouselValue: {
    fontSize: 12,
    fontWeight: '700' as const,
  },
  heroCalorieRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'stretch' as const,
    gap: 20,
  },
  heroRingWrap: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  heroRingContent: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  heroCalValueRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginTop: 2,
  },
  heroCalValue: {
    fontSize: 26,
    fontWeight: '800' as const,
    letterSpacing: -1,
    lineHeight: 30,
  },
  heroCalLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    marginTop: 6,
  },
  heroCalSubLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
    marginTop: 2,
    textTransform: 'capitalize' as const,
  },
  heroDetailsCol: {
    flex: 1,
    gap: 8,
    justifyContent: 'center' as const,
  },
  heroSimpleRow: {
    flexDirection: 'row' as const,
    alignItems: 'baseline' as const,
    gap: 4,
  },
  heroSimpleLabel: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  heroSimpleSeparator: {
    fontSize: 13,
    fontWeight: '500' as const,
  },
  heroSimpleValue: {
    fontSize: 13,
    fontWeight: '700' as const,
  },
  heroStatRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  heroStatLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    flex: 1,
  },
  heroStatValue: {
    fontSize: 13,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
  },
  heroRemainingDivider: {
    height: 1,
    alignSelf: 'stretch' as const,
    marginVertical: 6,
  },
  heroRemainingLabel: {
    fontSize: 10,
    fontWeight: '700' as const,
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
    textAlign: 'right' as const,
  },
  heroRemainingValue: {
    fontSize: 26,
    fontWeight: '800' as const,
    letterSpacing: -1.2,
    textAlign: 'right' as const,
    lineHeight: 30,
  },
  macroCardsRow: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  macroMiniCard: {
    flex: 1,
    gap: 8,
  },
  macroMiniRingRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  macroMiniInfo: {
    flex: 1,
    gap: 1,
  },
  macroMiniValues: {
    fontSize: 14,
    fontWeight: '700' as const,
  },
  macroMiniCurrent: {
    fontSize: 15,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  macroMiniTarget: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  macroMiniBar: {
    height: 4,
    borderRadius: 2,
    overflow: 'hidden' as const,
  },
  macroMiniBarFill: {
    height: '100%' as const,
    borderRadius: 2,
  },
  macroMiniName: {
    fontSize: 11,
    fontWeight: '600' as const,
  },
  carouselDots: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginTop: 10,
  },
  carouselDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  microCardTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
    alignSelf: 'flex-start' as const,
  },
  microCardSubtitle: {
    fontSize: 12,
    fontWeight: '500' as const,
    alignSelf: 'flex-start' as const,
    marginTop: 4,
  },
  combinedCard: {
    marginHorizontal: 20,
    marginBottom: 14,
    borderRadius: 14,
    padding: 24,
    borderWidth: 1,
    alignItems: 'center',
    gap: 0,
  },
  combinedDivider: {
    height: 1,
    alignSelf: 'stretch',
    marginVertical: 16,
  },
  macroRingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'stretch',
    gap: 8,
  },
  mainRingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainRingContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainCalorieValue: {
    fontSize: 48,
    fontWeight: '800' as const,
    lineHeight: 54,
    letterSpacing: -2,
  },
  mainCalorieTarget: {
    fontSize: 20,
    fontWeight: '600' as const,
    marginTop: 4,
  },
  mainCalorieLabel: {
    fontSize: 14,
    marginTop: 4,
  },
  overIndicator: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: 'rgba(197, 48, 48, 0.08)',
    borderRadius: 12,
  },
  overIndicatorText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: '#C53030',
    opacity: 0.8,
  },
  targetIndicator: {
    marginTop: 8,
  },
  targetIndicatorText: {
    fontSize: 12,
    fontWeight: '500' as const,
  },
  microsCard: {
    marginHorizontal: 20,
    marginBottom: 14,
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
  },
  miniMacroRingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 8,
  },
  microLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 0.3,
    textTransform: 'uppercase' as const,
  },
  waterCard: {
    marginHorizontal: 20,
    marginBottom: 14,
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    gap: 12,
  },
  exerciseCard: {
    marginHorizontal: 20,
    marginBottom: 14,
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    gap: 14,
  },

  activityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  activityTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
  },
  activityLogBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  activityLogBtnText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  activityStatsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    alignSelf: 'stretch',
  },
  activityStatCard: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 12,
  },
  activityStatValue: {
    fontSize: 18,
    fontWeight: '700' as const,
  },
  activityStatLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
  },
  activityBreakdownCard: {
    alignSelf: 'stretch',
    marginTop: 12,
    borderRadius: 10,
    padding: 12,
    gap: 6,
  },
  activityBreakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  activityBreakdownLabel: {
    fontSize: 12,
  },
  activityBreakdownValue: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  extraNutrientsCard: {
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    gap: 14,
  },
  extraNutrientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  extraNutrientInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: 72,
  },
  extraNutrientDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  extraNutrientName: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  extraNutrientBarContainer: {
    flex: 1,
  },
  extraNutrientBarBg: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  extraNutrientBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  extraNutrientValue: {
    fontSize: 11,
    fontWeight: '500' as const,
    minWidth: 72,
    textAlign: 'right' as const,
  },
  waterSection: {
    borderTopWidth: 1,
    paddingTop: 14,
    gap: 10,
  },
  nutrientTrackerSection: {
    gap: 10,
  },
  nutrientIconDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },

  waterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  waterTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  waterCount: {
    fontSize: 13,
    marginLeft: 'auto',
  },
  waterCupsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  waterBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  waterCupsDisplay: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  waterCupDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  macroRing: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  miniMacroRing: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  miniMacroRingValue: {
    fontSize: 15,
    fontWeight: '700' as const,
  },
  miniMacroControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
  },
  miniControlBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  macroRingContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  macroRingValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  },
  macroRingLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 0.3,
    textTransform: 'uppercase' as const,
  },
  macroRingTarget: {
    fontSize: 11,
  },
  mealTimeLabel: {
    fontSize: 17,
    fontWeight: '600' as const,
  },
  mealTime: {
    fontSize: 13,
  },
  deleteEntryButton: {
    padding: 4,
    marginTop: 4,
  },
  foodCalories: {
    fontSize: 13,
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
  },
  foodCount: {
    fontSize: 14,
    fontWeight: '500' as const,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyIcon: {
    marginBottom: 20,
    opacity: 0.3,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600' as const,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    lineHeight: 20,
  },
  foodList: {
    gap: 12,
  },
  foodItem: {
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
  },
  foodThumbnail: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  foodThumbnailImage: {
    width: '100%',
    height: '100%',
  },
  foodInfo: {
    flex: 1,
  },
  timeDeleteColumn: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  foodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  fabCircle: {
    position: 'absolute' as const,
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
    zIndex: 100,
  },
  catatAktivitasCardBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#F59E0B',
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  catatAktivitasCardBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  activityMiniStats: {
    flexDirection: 'row' as const,
    gap: 10,
    marginTop: 14,
    alignSelf: 'stretch' as const,
  },
  activityMiniStat: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  activityMiniStatVal: {
    fontSize: 12,
    fontWeight: '700' as const,
  },
  activitySeeAll: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  exModeTabs: {
    flexDirection: 'row' as const,
    borderRadius: 10,
    padding: 3,
    marginTop: 14,
    alignSelf: 'stretch' as const,
  },
  exModeTab: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
    paddingVertical: 8,
    borderRadius: 8,
  },
  exModeTabText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  exQuickContent: {
    alignSelf: 'stretch' as const,
    marginTop: 12,
    gap: 10,
  },
  exQuickChips: {
    gap: 8,
  },
  exQuickChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  exQuickChipEmoji: {
    fontSize: 16,
  },
  exQuickChipLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  exQuickInputRow: {
    flexDirection: 'row' as const,
    gap: 8,
    alignItems: 'center' as const,
  },
  exQuickInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  exLogBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#F59E0B',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  exDescribeContent: {
    alignSelf: 'stretch' as const,
    marginTop: 10,
  },
  exDescribeInputRow: {
    flexDirection: 'row' as const,
    gap: 8,
    alignItems: 'flex-end' as const,
  },
  exDescribeInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    maxHeight: 80,
    minHeight: 38,
  },
  exManualContent: {
    alignSelf: 'stretch' as const,
    marginTop: 10,
    gap: 8,
  },
  exManualInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  exManualRow: {
    flexDirection: 'row' as const,
    gap: 8,
  },
  exManualInputHalf: {
    flex: 1,
  },
  exManualLogBtn: {
    width: 'auto' as const,
    flexDirection: 'row' as const,
    gap: 6,
    paddingHorizontal: 16,
    alignSelf: 'flex-end' as const,
  },
  waterInCarousel: {
    alignSelf: 'stretch',
    gap: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContent: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700' as const,
  },
  modalBody: {
    padding: 24,
    gap: 20,
  },
  inputGroup: {
    gap: 8,
  },
  inputGroupHalf: {
    flex: 1,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  textInput: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  addButton: {
    backgroundColor: '#6C63FF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
  },
  addButtonDisabled: {
    opacity: 0.5,
  },
  addButtonText: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  bottomPadding: {
    height: 100,
  },
  analyzingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    gap: 16,
  },
  analyzingText: {
    fontSize: 16,
  },
  analysisContainer: {
    gap: 20,
    paddingBottom: 20,
  },
  photoPreview: {
    width: '100%',
    height: 200,
    borderRadius: 16,
  },
  confidenceBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  confidenceText: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  totalEstimate: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 14,
    marginBottom: 8,
  },
  totalCalories: {
    fontSize: 28,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  totalProtein: {
    fontSize: 16,
    fontWeight: '500' as const,
  },
  itemsList: {
    gap: 12,
  },
  itemsTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    marginBottom: 4,
  },
  foodItemCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600' as const,
    marginBottom: 4,
  },
  itemPortion: {
    fontSize: 14,
    marginBottom: 6,
  },
  itemCalories: {
    fontSize: 14,
  },
  tipsContainer: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
  },
  tipsTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    marginBottom: 8,
  },
  tipText: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 4,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  retakeButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  retakeText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  confirmButton: {
    flex: 2,
    backgroundColor: '#6C63FF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  confirmText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  bottomOptions: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  bottomOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 20,
  },
  bottomOptionText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  bottomOptionDivider: {
    height: 1,
  },
  pendingThumbnailContainer: {
    width: 48,
    height: 48,
    borderRadius: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  pendingThumbnail: {
    width: '100%',
    height: '100%',
  },
  pendingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingErrorOverlay: {
    backgroundColor: 'rgba(197, 48, 48, 0.2)',
  },

  foodDetailModalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  foodDetailModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  foodDetailModalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
  },
  foodDetailModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  foodDetailModalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
  },
  foodDetailModalBody: {
    padding: 20,
  },
  foodDetailName: {
    fontSize: 24,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  foodDetailTime: {
    fontSize: 14,
    marginBottom: 20,
  },
  foodDetailStatsContainer: {
    flexDirection: 'row',
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    marginBottom: 20,
  },
  foodDetailStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  foodDetailStatValue: {
    fontSize: 18,
    fontWeight: '700' as const,
    marginBottom: 2,
  },
  foodDetailStatLabel: {
    fontSize: 12,
  },
  foodDetailStatDivider: {
    width: 1,
    marginHorizontal: 8,
  },
  foodDetailItemsSection: {
    marginBottom: 20,
  },
  foodDetailItemsTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    marginBottom: 8,
  },
  foodDetailItemText: {
    fontSize: 14,
    lineHeight: 22,
  },
  foodDetailShareButton: {
    backgroundColor: '#6C63FF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  foodDetailShareButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  pendingModalScreen: {
    flex: 1,
    width: '100%',
  },
  pendingModalContent: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  pendingModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  pendingModalTitleContainer: {
    flex: 1,
    marginRight: 12,
  },
  pendingModalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
  },
  pendingModalSubtitle: {
    fontSize: 13,
    fontWeight: '500' as const,
    lineHeight: 16,
    marginTop: 2,
  },
  pendingModalBody: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  pendingModalBodyContent: {
    paddingBottom: 120,
  },
  pendingModalImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: 20,
  },
  pendingAnalyzingState: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  pendingAnalyzingText: {
    fontSize: 18,
    fontWeight: '600' as const,
  },
  pendingAnalyzingSubtext: {
    fontSize: 14,
  },
  pendingErrorState: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  pendingErrorText: {
    fontSize: 18,
    fontWeight: '600' as const,
  },
  pendingErrorSubtext: {
    fontSize: 14,
    textAlign: 'center',
  },
  pendingErrorButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  pendingRetryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  pendingRetryText: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  pendingDeleteButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  pendingDeleteText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#E5544B',
  },
  pendingResultState: {
    gap: 16,
    paddingBottom: 40,
  },
  pendingTotalCard: {
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
  },
  pendingHeroImageWrap: {
    width: '100%',
    aspectRatio: 4 / 5,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 12,
    position: 'relative',
  },
  pendingHeroImage: {
    width: '100%',
    height: '100%',
  },
  pendingHeroImageFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingImageCaloriesBadge: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  pendingImageCaloriesValue: {
    fontSize: 26,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  pendingImageCaloriesUnit: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  pendingStatsSection: {
    gap: 8,
  },
  pendingTotalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  pendingFoodName: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600' as const,
    lineHeight: 24,
    marginRight: 12,
  },
  pendingServingControls: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 8,
  },
  pendingServingBtn: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingServingText: {
    fontSize: 16,
    fontWeight: '600' as const,
    minWidth: 20,
    textAlign: 'center',
  },
  pendingCaloriesRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginBottom: 16,
  },
  pendingCaloriesEmoji: {
    fontSize: 24,
  },
  pendingCaloriesValue: {
    fontSize: 34,
    fontWeight: '800' as const,
    letterSpacing: -1,
  },
  pendingCaloriesUnit: {
    fontSize: 16,
  },
  pendingMacros: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  pendingMacro: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  pendingMacroEmoji: {
    fontSize: 20,
  },
  pendingMacroValue: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  pendingMacroLabel: {
    fontSize: 12,
  },
  pendingMicrosRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  pendingMicro: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  pendingMicroValue: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  pendingMicroLabel: {
    fontSize: 11,
  },
  pendingModalFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  pendingItemsTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    marginTop: 8,
  },
  pendingItemCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  pendingItemName: {
    fontSize: 15,
    fontWeight: '500' as const,
    marginBottom: 2,
  },
  pendingItemPortion: {
    fontSize: 13,
  },
  pendingItemCalories: {
    fontSize: 14,
  },
  itemRightSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  itemsTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
  },
  addItemButtonText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#22C55E',
  },
  editItemCard: {
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    gap: 12,
  },
  editItemTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    marginBottom: 4,
  },
  editItemRow: {
    gap: 4,
  },
  editItemRowMulti: {
    flexDirection: 'row',
    gap: 12,
  },
  editItemField: {
    flex: 1,
  },
  editItemFieldSmall: {
    flex: 1,
  },
  editItemLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginBottom: 4,
  },
  editItemInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  editItemActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  editItemDeleteBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editItemCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
  },
  editItemCancelText: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  editItemSaveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#22C55E',
    alignItems: 'center',
  },
  editItemSaveText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  confirmEditedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#22C55E',
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 4,
  },
  confirmEditedText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  pendingResultButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  pendingCancelButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  pendingCancelText: {
    fontSize: 16,
    fontWeight: '600' as const,
  },
  pendingConfirmButton: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#22C55E',
  },
  pendingConfirmText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  viewEntryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  viewEntryTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  viewEntrySubtitle: {
    fontSize: 13,
  },
  viewEntryImageContainer: {
    width: '100%',
    height: 200,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  viewEntryTimeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  viewEntryTimeText: {
    fontSize: 14,
    fontWeight: '500' as const,
  },
  shareStoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
  },
  shareStoryText: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  pendingHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  favoriteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#22C55E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  favoriteToast: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    right: 20,
    backgroundColor: '#22C55E',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  favoriteToastText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  suggestFavoriteToast: {
    position: 'absolute',
    bottom: 120,
    left: 24,
    right: 24,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  suggestFavoriteText: {
    fontSize: 15,
    fontWeight: '600' as const,
    marginBottom: 12,
    textAlign: 'center',
  },
  suggestFavoriteButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  suggestFavoriteBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  suggestFavoriteBtnText: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  addFoodModalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  addFoodModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  addFoodModalContent: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%',
  },
  addFoodModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
  },
  addFoodModalTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  tabActive: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600' as const,
  },
  addFoodModalBody: {
    padding: 20,
    maxHeight: 400,
  },
  mealList: {
    gap: 10,
  },
  mealItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  mealItemInfo: {
    flex: 1,
    flexShrink: 1,
    marginRight: 12,
  },
  mealItemContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  removeRecentButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  mealItemNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
    flex: 1,
  },
  mealItemName: {
    fontSize: 15,
    fontWeight: '600' as const,
    flex: 1,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  mealItemCalories: {
    fontSize: 13,
    marginTop: 4,
  },
  emptyMealList: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 8,
  },
  emptyMealText: {
    fontSize: 16,
    fontWeight: '600' as const,
    marginTop: 8,
  },
  emptyMealSubtext: {
    fontSize: 13,
  },
  addFoodModalFooter: {
    padding: 20,
    paddingBottom: 40,
  },
  quickExerciseModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  quickExerciseModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  quickExerciseModalContent: {
    width: '85%',
    maxWidth: 400,
    borderRadius: 20,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  quickExerciseModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  quickExerciseModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  quickExerciseModalTitleText: {
    flex: 1,
  },
  quickExerciseModalTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  quickExerciseModalSubtitle: {
    fontSize: 13,
  },
  quickExerciseModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickExerciseModalBody: {
    padding: 20,
    gap: 16,
  },
  quickExerciseModalLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
  },
  quickExerciseModalInputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  quickExerciseModalInput: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    fontSize: 16,
  },
  quickExerciseModalButton: {
    backgroundColor: '#4CAF7D',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  quickExerciseModalButtonDisabled: {
    opacity: 0.5,
  },
  quickExerciseModalButtonText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  manualEntryButton: {
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
  },
  manualEntryText: {
    fontSize: 15,
    fontWeight: '600' as const,
  },
  optionalImagePicker: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
  },
  optionalImagePlaceholder: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 20,
  },
  optionalImageText: {
    fontSize: 14,
    fontWeight: '500' as const,
  },
  optionalImagePreviewContainer: {
    position: 'relative',
  },
  optionalImagePreview: {
    width: '100%',
    height: 120,
    borderRadius: 12,
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    flex: 1,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 16,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
  },
  searchLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  searchLoadingText: {
    fontSize: 14,
  },
  searchErrorContainer: {
    padding: 16,
    alignItems: 'center',
  },
  searchErrorText: {
    fontSize: 14,
    color: '#E5544B',
  },
  usdaBrandName: {
    fontSize: 12,
    marginTop: 2,
  },
  usdaNutrientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  usdaMacros: {
    fontSize: 11,
  },
  searchSectionTitle: {
    fontSize: 12,
    fontWeight: '600' as const,
    marginBottom: 8,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  supabaseFoodImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    marginRight: 12,
  },
  healthScoreCard: {
    marginHorizontal: 24,
    marginBottom: 24,
    borderRadius: 12,
    padding: 18,
    borderWidth: 1,
  },
  healthScoreHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 14,
  },
  healthScoreTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  },
  healthScoreValue: {
    fontSize: 20,
    fontWeight: '800' as const,
    letterSpacing: -0.5,
  },
  healthScoreBarBg: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden' as const,
    marginBottom: 14,
  },
  healthScoreBarFill: {
    height: '100%' as const,
    borderRadius: 4,
  },
  healthScoreMessage: {
    fontSize: 14,
    fontWeight: '500' as const,
    lineHeight: 20,
  },
});
