import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F6F4F1' },
  scrollContent: { flexGrow: 1, padding: 20 },
  backButtonTop: { marginBottom: 12, alignSelf: 'flex-start' },
  progressBarContainer: { marginBottom: 24 },
  progressBar: {
    height: 3,
    backgroundColor: '#EEEDF2',
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#22C55E',
    borderRadius: 2,
  },
  contentWrapper: { flex: 1 },
  stepContainer: { flex: 1, justifyContent: 'space-between' },
  /** Use on long forms inside ScrollView so content scrolls above the keyboard (e.g. Simpan Progress Anda). */
  stepContainerSignIn: { flex: 0, justifyContent: 'flex-start' },
  signInFormNatural: { flex: 0 },

  heroContainer: { alignItems: 'center', marginTop: 20 },
  iconCircleLarge: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: 'rgba(108, 99, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 48,
  },
  heroTitle: {
    fontSize: 40,
    fontWeight: '700',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 48,
  },
  heroSubtitle: {
    fontSize: 18,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 28,
    paddingHorizontal: 16,
  },

  introContainer: {
    flex: 1,
    backgroundColor: '#F6F4F1',
  },
  introImageHero: {
    alignSelf: 'center',
    width: '85%',
    aspectRatio: 0.75,
    maxHeight: '55%',
    position: 'relative' as const,
    marginTop: 56,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
  },
  introImageLarge: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  introFloatingBadge: {
    position: 'absolute' as const,
    bottom: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(34, 197, 94, 0.95)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  introFloatingBadgeText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  introHeroSection: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  introTextSection: {
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  introBrandTitle: {
    fontSize: 42,
    fontWeight: '800' as const,
    color: '#111827',
    marginBottom: 12,
    letterSpacing: -1,
  },
  introTagline: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    maxWidth: 320,
  },
  introCtaSection: {
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  introPrimaryButton: {
    backgroundColor: '#22C55E',
    borderRadius: 28,
    paddingVertical: 18,
    paddingHorizontal: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 6,
  },
  introPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  introButtonIconCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  introSignInLink: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    paddingVertical: 8,
  },
  introSignInText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  introSignInTextBold: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#22C55E',
  },

  questionContainer: { marginBottom: 24 },
  questionTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#1A1A2E',
    marginBottom: 10,
    lineHeight: 34,
  },
  questionSubtitle: { fontSize: 16, color: '#6E6E82', lineHeight: 24 },

  optionsList: { gap: 12, marginBottom: 24 },
  activityCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    padding: 20,
  },
  activityCardActive: { borderColor: '#22C55E', backgroundColor: 'rgba(34, 197, 94, 0.06)' },
  activityCardTitle: { fontSize: 18, fontWeight: '600', color: '#666666', marginBottom: 6 },
  activityCardTitleActive: { color: '#000000' },
  activityCardDesc: { fontSize: 14, color: '#666666', lineHeight: 20 },

  goalCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  goalCardActive: { borderColor: '#22C55E', backgroundColor: 'rgba(34, 197, 94, 0.06)' },
  goalIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalIcon: { fontSize: 20 },
  goalTextContainer: { flex: 1 },
  goalCardTitle: { fontSize: 15, fontWeight: '600' as const, color: '#666666', marginBottom: 3 },
  goalCardTitleActive: { color: '#000000' },
  goalCardDesc: { fontSize: 12, color: '#666666', lineHeight: 16 },

  primaryButton: {
    backgroundColor: '#22C55E',
    borderRadius: 28,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonDisabled: { opacity: 0.4 },
  primaryButtonText: { fontSize: 18, fontWeight: '600', color: '#FFFFFF' },

  genderOptions: { flexDirection: 'row', gap: 16, marginBottom: 24 },
  genderCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 28,
    padding: 28,
    alignItems: 'center',
    gap: 16,
  },
  genderCardActive: { borderColor: '#22C55E', backgroundColor: 'rgba(34, 197, 94, 0.06)' },
  genderIconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderIconCircleActive: { backgroundColor: 'rgba(34, 197, 94, 0.12)' },
  genderText: { fontSize: 20, fontWeight: '600', color: '#666666' },
  genderTextActive: { color: '#000000' },

  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  circularProgressContainer: {
    width: 140,
    height: 140,
    marginBottom: 40,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circularProgressTextContainer: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  loadingTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#000000',
    textAlign: 'center',
    lineHeight: 36,
    marginBottom: 16,
  },
  loadingSubtext: { fontSize: 16, color: '#666666', textAlign: 'center' },

  reassuranceContainer: { alignItems: 'center', marginTop: 20 },
  reassuranceIconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  reassuranceTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 40,
  },
  reassuranceSubtitle: { fontSize: 17, color: '#666666', textAlign: 'center', lineHeight: 26, paddingHorizontal: 32 },

  inputSection: { flex: 1, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 20,
    gap: 12,
  },
  numberInput: {
    fontSize: 48,
    fontWeight: '700' as const,
    color: '#000000',
    minWidth: 100,
    textAlign: 'center',
    paddingVertical: 0,
  },
  inputUnit: { fontSize: 24, fontWeight: '600' as const, color: '#666666' },

  dateButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    paddingHorizontal: 32,
    paddingVertical: 24,
  },
  dateButtonText: { fontSize: 24, fontWeight: '600' as const, color: '#000000', textAlign: 'center' },
  iosDatePicker: { height: 200 },

  comparisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    padding: 28,
  },
  comparisonItem: { flex: 1, alignItems: 'center', gap: 8 },
  comparisonLabel: { fontSize: 14, color: '#666666', fontWeight: '600' as const, textAlign: 'center' },
  comparisonValue: { fontSize: 28, fontWeight: '700' as const, color: '#000000', textAlign: 'center' },
  comparisonUnit: { fontSize: 18, fontWeight: '600' as const, color: '#666666' },
  weightValueRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center' },
  comparisonValueNum: { fontSize: 28, fontWeight: '700' as const, color: '#000000' },
  comparisonUnitInline: { fontSize: 16, fontWeight: '600' as const, color: '#666666', marginLeft: 4 },
  targetWeightInput: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#000000',
    paddingVertical: 0,
    paddingHorizontal: 0,
    minWidth: 50,
    textAlign: 'center',
  },
  inlineInputRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', gap: 8 },
  inlineNumberInput: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#000000',
    paddingVertical: 0,
    paddingHorizontal: 0,
    minWidth: 60,
    textAlign: 'center',
  },
  inlineHintLine: {
    width: 70,
    height: 2,
    backgroundColor: '#E5E5E5',
    borderRadius: 2,
    marginTop: 4,
  },

  introImage: { width: 90, height: 90 },

  languageToggle: {
    position: 'absolute' as const,
    top: 8,
    right: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(34, 197, 94, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.12)',
    zIndex: 10,
  },
  languageText: { fontSize: 12, fontWeight: '600' as const, color: '#22C55E' },

  signInLink: { marginTop: 20, padding: 12, alignItems: 'center' },
  signInLinkText: { fontSize: 15, fontWeight: '600' as const, color: '#666666' },

  notificationButtons: { gap: 12 },
  skipButton: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 28,
    padding: 20,
    alignItems: 'center',
  },
  skipButtonText: { fontSize: 18, fontWeight: '600' as const, color: '#6E6E82' },

  finalScrollView: { flex: 1 },
  finalScrollContent: { flexGrow: 1 },
  finalPlanContainer: { alignItems: 'center' },
  finalPlanTitle: { fontSize: 26, fontWeight: '700', color: '#000000', textAlign: 'center', marginBottom: 20, lineHeight: 32 },
  projectionBanner: {
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
    borderWidth: 2,
    borderColor: 'rgba(34, 197, 94, 0.2)',
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginBottom: 32,
    alignItems: 'center',
    width: '100%',
  },
  projectionLabel: { fontSize: 14, color: '#6E6E82', marginBottom: 4, textAlign: 'center' },
  projectionWeight: { fontSize: 40, fontWeight: '700' as const, color: '#22C55E', marginBottom: 4, textAlign: 'center' },
  projectionDate: { fontSize: 16, color: '#22C55E', fontWeight: '600' as const, textAlign: 'center' },

  donutChartContainer: { width: 200, height: 200, marginBottom: 20, position: 'relative', alignItems: 'center', justifyContent: 'center' },
  donutCenter: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  donutCenterValue: { fontSize: 40, fontWeight: '700' as const, color: '#000000' },
  donutCenterLabel: { fontSize: 12, color: '#666666', marginTop: 2 },
  macroLegend: { flexDirection: 'row', gap: 12, marginBottom: 28, flexWrap: 'wrap', justifyContent: 'center' },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 12, height: 12, borderRadius: 6 },
  legendText: { fontSize: 12, color: '#666666' },

  tipsSection: { width: '100%', gap: 12, marginBottom: 24 },
  tipsSectionTitle: { fontSize: 18, fontWeight: '600' as const, color: '#000000', marginBottom: 8 },
  tipCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 24, padding: 16, gap: 12 },
  tipIconCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(34, 197, 94, 0.08)', alignItems: 'center', justifyContent: 'center' },
  tipIcon: { fontSize: 22 },
  tipContent: { flex: 1 },
  tipTitle: { fontSize: 15, fontWeight: '600' as const, color: '#000000', marginBottom: 2 },
  tipDesc: { fontSize: 13, color: '#666666', lineHeight: 18 },

  subscriptionOverlay: { position: 'absolute' as const, top: 0, left: 0, right: 0, bottom: 0, zIndex: 1000 },
  subscriptionBackdrop: { position: 'absolute' as const, top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.7)' },
  subscriptionModal: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    padding: 24,
    maxHeight: '90%',
  },
  subscriptionClose: { alignSelf: 'flex-end', padding: 8, marginBottom: 16 },
  subscriptionHeroImage: { width: '100%', height: 160, borderRadius: 20, marginBottom: 20 },
  subscriptionTitle: { fontSize: 24, fontWeight: '700' as const, color: '#000000', textAlign: 'center', marginBottom: 10, lineHeight: 32 },
  subscriptionSubtitle: { fontSize: 15, color: '#666666', textAlign: 'center', lineHeight: 22, marginBottom: 24, paddingHorizontal: 8 },
  subscriptionPriceCard: { backgroundColor: '#FFFFFF', borderWidth: 1.5, borderColor: '#EEEDF2', borderRadius: 24, padding: 16, marginBottom: 12 },
  subscriptionPriceCardActive: { borderColor: '#22C55E', backgroundColor: 'rgba(34, 197, 94, 0.06)' },
  subscriptionPriceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  subscriptionPlanLabel: { fontSize: 14, color: '#666666', marginBottom: 4 },
  subscriptionPlanPrice: { fontSize: 18, fontWeight: '700' as const, color: '#22C55E' },
  subscriptionMonthlyEquiv: { fontSize: 13, color: '#666666', marginTop: 4 },
  subscriptionButton: { backgroundColor: '#22C55E', borderRadius: 28, padding: 18, alignItems: 'center', marginBottom: 16 },
  subscriptionButtonText: { fontSize: 18, fontWeight: '600' as const, color: '#FFFFFF', marginBottom: 4 },
  subscriptionButtonSubtext: { fontSize: 13, color: 'rgba(255, 255, 255, 0.8)' },
  subscriptionFooter: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  subscriptionFooterLink: { fontSize: 12, color: '#666666' },
  subscriptionFooterDivider: { fontSize: 12, color: '#999999' },
  subscriptionPopularBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#22C55E',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 8,
  },
  subscriptionPopularBadgeText: { fontSize: 11, fontWeight: '700' as const, color: '#FFFFFF' },
  subscriptionSavingsText: { fontSize: 13, fontWeight: '600' as const, color: '#16A34A', marginTop: 6 },
  subscriptionYearCardHighlight: { borderColor: '#22C55E', borderWidth: 2, backgroundColor: 'rgba(34, 197, 94, 0.06)' },
  subscriptionRestoreTextBtn: { paddingVertical: 14, alignItems: 'center' },
  subscriptionRestoreTextBtnLabel: { fontSize: 15, fontWeight: '700' as const, color: '#22C55E' },
  subscriptionFootnoteTrial: { fontSize: 12, color: '#666666', textAlign: 'center', lineHeight: 18, marginTop: 8 },

  healthFeatures: {
    gap: 14,
    marginBottom: 32,
  },
  healthFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  healthFeatureDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  healthFeatureText: {
    fontSize: 15,
    color: '#333333',
    fontWeight: '500' as const,
  },

  header: { alignItems: 'center', marginBottom: 32 },
  iconCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: 'rgba(34, 197, 94, 0.08)', alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  signInTitle: { fontSize: 28, fontWeight: '700' as const, color: '#000000', textAlign: 'center', marginBottom: 12 },
  signInSubtitle: { fontSize: 16, color: '#666666', textAlign: 'center', lineHeight: 24 },

  signInForm: { flex: 1 },
  inputGroup: { marginBottom: 20 },
  inputLabel: { fontSize: 15, fontWeight: '600' as const, color: '#000000', marginBottom: 8 },
  signInInput: { backgroundColor: '#FFFFFF', borderWidth: 1.5, borderColor: '#EEEDF2', borderRadius: 24, paddingHorizontal: 20, paddingVertical: 16, fontSize: 16, color: '#1A1A2E' },
  signInPasswordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    paddingRight: 8,
  },
  signInPasswordInput: {
    flex: 1,
    paddingLeft: 20,
    paddingVertical: 16,
    paddingRight: 8,
    fontSize: 16,
    color: '#1A1A2E',
  },
  signInPasswordToggle: { padding: 10 },

  divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 24 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#E5E5E5' },
  dividerText: { fontSize: 14, color: '#999999', marginHorizontal: 16 },

  googleButton: { backgroundColor: '#FFFFFF', borderWidth: 1.5, borderColor: '#EEEDF2', borderRadius: 28, padding: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12 },
  googleButtonText: { fontSize: 16, fontWeight: '600' as const, color: '#000000' },

  skipSignInButton: { padding: 16, alignItems: 'center', marginTop: 16 },
  skipSignInButtonText: { fontSize: 16, fontWeight: '600' as const, color: '#666666' },

  thankYouContainer: {
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 48,
  },
  thankYouIconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  thankYouEmoji: {
    fontSize: 64,
  },
  thankYouTitle: {
    fontSize: 36,
    fontWeight: '700' as const,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 16,
  },
  thankYouSubtitle: {
    fontSize: 17,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 26,
    paddingHorizontal: 24,
  },
  nameInputSection: {
    marginBottom: 32,
  },
  nameInputLabel: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#000000',
    marginBottom: 12,
  },
  nameInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#EEEDF2',
    borderRadius: 24,
    padding: 20,
    fontSize: 18,
    color: '#1A1A2E',
    marginBottom: 12,
  },
  nameInputHelper: {
    fontSize: 14,
    color: '#999999',
    lineHeight: 20,
  },

  inputWrapperWarning: { borderColor: '#EF4444', backgroundColor: 'rgba(239, 68, 68, 0.06)' },
  numberInputWarning: { color: '#EF4444' },
  inputUnitWarning: { color: '#EF4444' },

  recommendationCard: {
    marginTop: 14,
    width: '100%',
    backgroundColor: 'rgba(239, 68, 68, 0.06)',
    borderWidth: 2,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    borderRadius: 16,
    padding: 14,
  },
  recommendationTitle: { fontSize: 14, fontWeight: '700' as const, color: '#111827', marginBottom: 6 },
  recommendationText: { fontSize: 13, color: '#374151', lineHeight: 18, marginBottom: 12 },
  recommendationButton: { backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: 'rgba(239, 68, 68, 0.35)', borderRadius: 14, paddingVertical: 12, paddingHorizontal: 14, alignItems: 'center' },
  recommendationButtonText: { fontSize: 14, fontWeight: '700' as const, color: '#EF4444' },

  validationWarning: {
    marginTop: 16,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
    borderRadius: 12,
    padding: 14,
  },
  validationWarningText: {
    fontSize: 14,
    color: '#B45309',
    textAlign: 'center',
    lineHeight: 20,
  },

});
