import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const storyShareStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0f',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingHorizontal: 20,
  },
  previewContainer: {
    aspectRatio: 9 / 16,
    width: SCREEN_WIDTH - 80,
    alignSelf: 'center',
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1a1a2e',
    marginBottom: 24,
  },
  headerShareButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(108, 99, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topInfoContainer: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 8,
  },
  topInfoPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  topInfoText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  previewImage: {
    ...StyleSheet.absoluteFillObject,
  },
  previewGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  previewContent: {
    position: 'absolute',
    bottom: 36,
    left: 20,
    right: 20,
    alignItems: 'flex-start',
  },
  previewContentMinimal: {
    bottom: 60,
    alignItems: 'center',
  },
  previewMealName: {
    fontSize: 21,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  previewMealNameLarge: {
    fontSize: 32,
    marginBottom: 8,
  },
  caloriesBlock: {
    marginBottom: 12,
  },
  previewCalories: {
    fontSize: 44,
    fontWeight: '800' as const,
    color: '#FFFFFF',
  },
  previewCaloriesHero: {
    fontSize: 64,
  },
  trackedByContainer: {
    marginTop: 4,
  },
  trackedByText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: 'rgba(255,255,255,0.7)',
  },
  trackedByBrand: {
    fontWeight: '700' as const,
    color: '#22C55E',
  },
  previewCaloriesUnit: {
    fontSize: 20,
    fontWeight: '500' as const,
  },
  macroChips: {
    flexDirection: 'column',
    marginBottom: 10,
  },
  macroChipsSpaced: {
    marginBottom: 0,
  },
  macroInlineText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: 'rgba(255,255,255,0.95)',
  },
  previewPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  previewPillText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  toggleTextContainer: {
    flex: 1,
    flexShrink: 1,
  },
  nameEditInput: {
    fontSize: 13,
    color: '#22C55E',
    marginTop: 2,
    paddingVertical: 4,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#22C55E',
  },
  nameEditTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  editIcon: {
    marginLeft: 6,
  },
  includePanel: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  includePanelTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
    marginBottom: 16,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  toggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  },
  toggleIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleIconActive: {
    backgroundColor: 'rgba(108, 99, 255, 0.3)',
  },
  toggleLabel: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: '#FFFFFF',
  },
  toggleSubtitle: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  toggleCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleCheckActive: {
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
  },
  watermarkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
  },
  watermarkLabel: {
    fontSize: 14,
    color: '#999',
  },
  shareSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1a1a24',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  shareGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  shareAppItem: {
    alignItems: 'center',
    width: (SCREEN_WIDTH - 40 - 48) / 4,
  },
  shareAppIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  shareAppIconOutline: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  shareAppEmoji: {
    fontSize: 24,
  },
  shareAppLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: '#999',
    textAlign: 'center' as const,
    lineHeight: 14,
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  locationSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1a1a24',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    marginBottom: 24,
  },
  locationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  locationOptionIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(108, 99, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  locationOptionText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500' as const,
    color: '#FFFFFF',
  },
  customLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    marginBottom: 20,
  },
  customLocationIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(236, 72, 153, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  customLocationInput: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    paddingVertical: 8,
  },
  addLocationBtn: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#22C55E',
    paddingHorizontal: 12,
  },
  presetsTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#666',
    marginBottom: 12,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  presetsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  presetChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 24,
  },
  presetIcon: {
    fontSize: 16,
  },
  presetText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#FFFFFF',
  },
  removeLocationBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 8,
  },
  removeLocationText: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: '#EF4444',
  },
});
